version: "3.6"
services:
  app:
    build: .
    image: management-service-api:tag
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:14.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: management-service
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
